// Enriches today's Amelia bookings with order details from the HOV Lagersystem.
// Reads data/bookings.js, logs into the Lagersystem, queries each customer's MTM
// orders directly via Supabase REST, and writes the enriched bookings back.
//
// Run AFTER scrape-bookings.js (which populates the initial bookings list).

const fs = require('fs');
const path = require('path');

(function loadEnv(){
  const envFile = path.join(__dirname, '.env');
  if (!fs.existsSync(envFile)) return;
  fs.readFileSync(envFile, 'utf8').split(/\r?\n/).forEach((line) => {
    const m = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$/);
    if (!m) return;
    let v = m[2];
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1);
    if (!process.env[m[1]]) process.env[m[1]] = v;
  });
})();

const BOOKINGS_FILE = path.resolve(__dirname, 'checklist', 'data', 'bookings.js');
const LAGER_URL = 'https://houseofvinterberg.netlify.app/mtm-ordrer';
const SB_URL = 'https://awmpgxdetxqlpkchcvlh.supabase.co';
const MTM_CHANNEL_ID = 'c92bd07c-fc3a-44fd-9059-77d1fa4dac37';
const ARCHIVED_TABLE = 'archived_mtm_orders';

function readBookings(){
  if (!fs.existsSync(BOOKINGS_FILE)) return { bookings:[], delivery:0, updated:null };
  const content = fs.readFileSync(BOOKINGS_FILE, 'utf8');
  const arrMatch = content.match(/window\.HOV_BOOKINGS\s*=\s*(\[[\s\S]*?\]);/);
  const deliveryMatch = content.match(/window\.HOV_DELIVERY_COUNT\s*=\s*(\d+)/);
  const updatedMatch = content.match(/window\.HOV_BOOKINGS_UPDATED\s*=\s*(?:"([^"]*)"|(null))/);
  let bookings = [];
  if (arrMatch) {
    try { bookings = JSON.parse(arrMatch[1]); } catch(e){ console.error('parse error:', e.message); }
  }
  return {
    bookings,
    delivery: deliveryMatch ? parseInt(deliveryMatch[1], 10) : 0,
    updated: updatedMatch ? (updatedMatch[1] || null) : null,
  };
}

function writeBookings(bookings, delivery, updated){
  const out = '// Auto-generated by HOV-Monitor/enrich-orders.js at ' + new Date().toISOString() + '\n' +
    '// Do not edit by hand. The scraper + enricher overwrites this file on every run.\n' +
    'window.HOV_BOOKINGS = ' + JSON.stringify(bookings, null, 2) + ';\n' +
    'window.HOV_DELIVERY_COUNT = ' + JSON.stringify(delivery) + ';\n' +
    'window.HOV_BOOKINGS_UPDATED = ' + JSON.stringify(updated || new Date().toISOString()) + ';\n';
  fs.writeFileSync(BOOKINGS_FILE, out, 'utf8');
}

function buildOrderQuery(name){
  const safe = encodeURIComponent(name);
  return `${SB_URL}/rest/v1/orders?select=order_number,status,customer_name,customer_phone,customer_email,estimated_shipping_date,created_at,mtm_order_details_new(item,productType,cmtStatus,fabricStatus,dateNeeded,lineNumber)&customer_name=ilike.*${safe}*&order=created_at.desc&limit=5`;
}

function buildArchivedQuery(name){
  const safe = encodeURIComponent(name);
  return `${SB_URL}/rest/v1/${ARCHIVED_TABLE}?select=*&client=ilike.*${safe}*&order=date.desc&limit=5`;
}

function mergeOrderIntoBooking(b, order){
  if (!order) return b;
  const lines = Array.isArray(order.mtm_order_details_new) ? order.mtm_order_details_new : [];
  const items = lines.map(d => (d.item || d.productType || '').toString().trim()).filter(Boolean);
  return {
    ...b,
    orderId: String(order.order_number || b.orderId),
    item: items.length ? items.join(' . ') : (b.item && b.item !== '-' ? b.item : 'Ingen line items'),
    // Keep b.category (the Amelia service category, e.g. Opmåling/Fitting) untouched.
    // Keep b.employee untouched.
    // Notes stay strictly as the Amelia internal note (b.notes from scraper).
    _orderMatch: true,
  };
}

(async () => {
  const { bookings, delivery, updated } = readBookings();
  if (!bookings.length){
    console.log(JSON.stringify({ ok:true, message:'Ingen bookings at berige', count:0 }));
    return;
  }
  // Distinct names to query (handles duplicate customers)
  const names = Array.from(new Set(bookings.map(b => (b.name || '').replace(/ \+ \d+$/,'').trim()).filter(n => n && n !== 'Ukendt gæst' && n !== 'Mock')));
  if (!names.length){
    console.log(JSON.stringify({ ok:true, message:'Ingen rigtige navne at slå op', count:0 }));
    return;
  }

  let chromium;
  try { ({ chromium } = require('playwright')); }
  catch(e){ console.error('Playwright mangler. Kor install.ps1.'); process.exit(2); }

  const user = process.env.LAGER_USER || '';
  const pass = process.env.LAGER_PASS || '';
  if (!user || !pass){
    console.error('LAGER_USER/LAGER_PASS ikke sat i .env');
    process.exit(2);
  }

  const browser = await chromium.launch({ headless: true });
  const ctx = await browser.newContext({ viewport: { width:1366, height:900 } });
  const page = await ctx.newPage();

  let anonKey = null;
  page.on('request', (req) => {
    if (anonKey) return;
    const url = req.url();
    if (url.startsWith(SB_URL + '/rest/v1/')) {
      const h = req.headers();
      if (h.apikey) anonKey = h.apikey;
    }
  });

  try {
    await page.goto(LAGER_URL, { waitUntil:'domcontentloaded', timeout:30000 });
    await page.waitForLoadState('networkidle', { timeout:15000 }).catch(()=>{});

    const hasPwd = await page.$('input[type=password]').then(el => !!el);
    if (hasPwd){
      const emailEl = await page.$('input[type=email]') || await page.$('input[name=email]');
      const pwdEl = await page.$('input[type=password]');
      if (emailEl) await emailEl.fill(user);
      if (pwdEl) await pwdEl.fill(pass);
      const submit = await page.$('button[type=submit]') || await page.$('form button');
      if (!submit) throw new Error('Login-knap ikke fundet');
      await Promise.all([
        page.waitForLoadState('networkidle', { timeout:15000 }).catch(()=>{}),
        submit.click(),
      ]);
      await page.waitForTimeout(2500);
    }

    // Navigate to MTM orders so the page warms up the apikey + supabase session.
    await page.goto(LAGER_URL, { waitUntil:'domcontentloaded', timeout:20000 }).catch(()=>{});
    await page.waitForLoadState('networkidle', { timeout:15000 }).catch(()=>{});
    await page.waitForTimeout(3000);

    const accessToken = await page.evaluate(() => {
      const k = Object.keys(localStorage).find(x => x.startsWith('sb-') && x.endsWith('-auth-token'));
      if (!k) return null;
      try { return JSON.parse(localStorage.getItem(k)).access_token; } catch(e){ return null; }
    });

    if (!anonKey || !accessToken){
      throw new Error('Kunne ikke faa anonKey eller accessToken efter login');
    }

    // Helper that runs fetch in the page context (CORS + cookies handled by browser).
    async function fetchOrders(name){
      return await page.evaluate(async ({ url, anonKey, accessToken }) => {
        const r = await fetch(url, {
          headers: { 'apikey': anonKey, 'Authorization': 'Bearer ' + accessToken }
        });
        return { status: r.status, body: await r.json().catch(()=>null) };
      }, { url: buildOrderQuery(name), anonKey, accessToken });
    }

    // For each unique customer name, fetch their most recent orders.
    const ordersByName = {};
    for (const name of names) {
      try {
        const r = await fetchOrders(name);
        if (r.status === 200 && Array.isArray(r.body) && r.body.length){
          ordersByName[name] = r.body[0]; // most recent first
        } else {
          ordersByName[name] = null;
        }
      } catch(e){
        console.error('fetch failed for', name, ':', e.message);
        ordersByName[name] = null;
      }
    }

    // Merge order info into each booking by name match.
    const enriched = bookings.map(b => {
      const key = (b.name || '').replace(/ \+ \d+$/,'').trim();
      const order = ordersByName[key];
      return order ? mergeOrderIntoBooking(b, order) : b;
    });

    const matched = enriched.filter(b => b._orderMatch).length;
    const finalBookings = enriched.map(({_orderMatch, ...rest}) => rest);

    writeBookings(finalBookings, delivery, new Date().toISOString());
    console.log(JSON.stringify({
      ok: true,
      bookings: finalBookings.length,
      enriched: matched,
      lookups: names.length,
      missing: names.filter(n => !ordersByName[n]),
    }, null, 2));
  } finally {
    await ctx.close();
    await browser.close();
  }
})().catch((err) => {
  console.error('[enrich-orders] crash:', err && err.message || err);
  process.exit(2);
});
